### PR TITLE
Namespace updates

### PR DESCRIPTION
**Pull request by spladug**
Kevin's commit is me pulling the gofmt pass out of #10. I then just rename some strings a little.

:eyeglasses: @kjoconnor

### CODE REVIEW

**Comment by kjoconnor** [comment]
cool thanks! So will this require us to do some shuffling around of metrics/alerts/etc? :fish:

**Comment by kjoconnor** [comment]
Do we need to update the tests here? i.e., https://github.com/reddit/tallier/blob/master/tally/snapshot_test.go#L80

**Comment by kjoconnor** [comment]
:nail_care:

**Comment by spladug** [comment]
ok,thanks for catching that. i must not have run the test suite. i've fixed it up in both the commits that change stuff, and i've added travis support so i can't be this dumb again.

(check out that pretty green check mark)

:haircut:

**Comment by kjoconnor** [comment]
Excellent! :fish:

**Comment by spladug** [comment]
closing this until we prioritize working on it

**Pull request closed without merging**
